language: cpp
sudo: true

matrix:
  include:

    # Linux C++14 g++ build
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env: COMPILER='g++-6'

    # Linux C++14 clang++ build
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-precise-3.8', 'ubuntu-toolchain-r-test']
          packages: ['clang-3.8']
      env: COMPILER='clang++-3.8'

    # OSX C++14 Clang build
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: COMPILER='clang++'

install: true

before_script:
  - export CXX=${COMPILER}
  - cd ${TRAVIS_BUILD_DIR}

script:
  - cd C++
  - make -j 2
  - for test in $(find . -type f -name "*.test"); do ./$test; done
